#cloud-config
autoinstall:
  version: 1
  locale: pt_BR.UTF-8
  timezone: America/Fortaleza
  updates: all
  source:
    search_drivers: true
    id: ubuntu-desktop-minimal
  keyboard:
    layout: br
    variant: abnt
    toggle: null
  identity:
    realname: "Ubuntu User"
    username: ubuntu
    password: "ubuntu"
    hostname: ubuntu
  apt:
    mirror-selection:
      primary:
        - uri: "http://br.archive.ubuntu.com/ubuntu"
    geoip: true
  codecs:
    install: true
  drivers:
    install: true
  oem:
    install: true
  storage:
    layout:
      name: lvm
      password: "senha_segura"
      sizing-policy: all
    swap:
      size: 8GB
  snaps:
    - name: postman
      channel: latest/stable
      classic: false
    - name: android-studio
      channel: latest/stable
      classic: true
    - name: node
      channel: latest/edge
      classic: true
    - name: dotnet-sdk
      channel: latest/stable
      classic: true
    - name: discord
      channel: latest/stable
      classic: false
    - name: telegram-desktop
      channel: latest/stable
      classic: false
    - name: zoom-client
      channel: edge
      classic: false
    - name: firefox
      channel: latest/stable
      classic: false
    - name: google-cloud-sdk
      channel: latest/stable
      classic: true
    - name: google-cloud-cli
      channel: latest/stable
      classic: true
    - name: prometheus
      channel: edge
      classic: false
    - name: dcgm
      channel: latest/stable
      classic: false
    - name: vlc
      channel: edge
      classic: false
    - name: gabutdm
      channel: edge
      classic: false
    - name: foliate
      channel: latest/stable
      classic: false
    - name: okular
      channel: latest/stable
      classic: false
    - name: umlet-standalone
      channel: edge
      classic: false    
  packages:
    - wget
    - curl
    - git
    - ufw
    - micro
    - gh
    - build-essential
    - nvidia-driver-470
  shutdown: reboot
